runtime: php55
api_version: 1
threadsafe: yes

handlers:
# Serve images as static resources.
- url: /(.+\.(js|ico|gif|png|jpg|css))
  static_files: \1
  upload: .+\.(js|ico|gif|png|jpg|css)
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)
  script: \1

- url: /
  script: index.php

- url: /.*
  script: redir.php
